
language: android
android:
  components:
    - platform-tools
    - tools
     
    - build-tools

    - android-22

before_install:
  - git clone https://github.com/urho3d/android-ndk.git $HOME/android-ndk-home
  - export ANDROID_NDK_HOME=$HOME/android-ndk-home

script: ./gradlew build
